M48
; DRILL file {KiCad (6.0.11)} date Tue Aug 29 14:16:51 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-29T14:16:51-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X107.544Y-126.39
X110.998Y-43.18
X189.586Y-126.67
X198.882Y-43.18
T0
M30
