M48
; DRILL file {KiCad 7.0.9} date Tue Dec 12 15:16:29 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-12T15:16:29-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X107.544Y-126.39
X110.998Y-43.18
X189.586Y-126.67
X198.882Y-43.18
T0
M30
